### ISSUE TITLE
Spesifikasi

### ISSUE THREAD

**Issue by chae48** [agungsijawir/m910s-sonoma#1]
Bang, boleh tahu spesifikasi m910s nya?

**Comment by agungsijawir** [comment]
```
Processor: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
RAM: 4x4GB DDR4 2400 MHz
Storage: Sata SSD 240GB
VGA: Intel HD 630 (On Board VGA, Using DipslayPort)
WiFi Card: BCM4360 (BCM943602CS) - air drop ok, BT ok, WiFi ok
Ethernet: Intel I219-LM2 Gigabit Ethernet
BIOS: Default Lenovo 
AUDIO: Realtek ALC662 (ALC Layout 16)
```

Sebenarnya dual-boot juga sama windows, pake GTX 750TI, tp drivernya ga support sonoma ya sudah pake yang onboard intel aja. Kalau ada yang mau ditanyakan lagi, reply aja @chae48

**Comment by chae48** [comment]
> ```
> Processor: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
> RAM: 4x4GB DDR4 2400 MHz
> Storage: Sata SSD 240GB
> VGA: Intel HD 630 (On Board VGA, Using DipslayPort)
> WiFi Card: BCM4360 (BCM943602CS) - air drop ok, BT ok, WiFi ok
> Ethernet: Intel I219-LM2 Gigabit Ethernet
> BIOS: Default Lenovo 
> AUDIO: Realtek ALC662 (ALC Layout 16)
> ```
> 
> Sebenarnya dual-boot juga sama windows, pake GTX 750TI, tp drivernya ga support sonoma ya sudah pake yang onboard intel aja. Kalau ada yang mau ditanyakan lagi, reply aja @chae48

Punya saya yg versi i5-6600, onboard vga HD 530, ethernet intel I219-LM, tanpa wifi card.
Pakai punya abang ini bisa kah bang?

**Comment by agungsijawir** [comment]
> > ```
> > Processor: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
> > RAM: 4x4GB DDR4 2400 MHz
> > Storage: Sata SSD 240GB
> > VGA: Intel HD 630 (On Board VGA, Using DipslayPort)
> > WiFi Card: BCM4360 (BCM943602CS) - air drop ok, BT ok, WiFi ok
> > Ethernet: Intel I219-LM2 Gigabit Ethernet
> > BIOS: Default Lenovo 
> > AUDIO: Realtek ALC662 (ALC Layout 16)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Sebenarnya dual-boot juga sama windows, pake GTX 750TI, tp drivernya ga support sonoma ya sudah pake yang onboard intel aja. Kalau ada yang mau ditanyakan lagi, reply aja @chae48
> 
> Punya saya yg versi i5-6600, onboard vga HD 530, ethernet intel I219-LM, tanpa wifi card. Pakai punya abang ini bisa kah bang?

ane ga rekomendasi ya. tp kalau mau jajal sampai boot via usb, monggo aja dicoba.
